### ISSUE TITLE
Spotify cannot log in

### ISSUE THREAD

**Issue by eirik616** [mopidy/pyspotify#194]
When i try to start mopidy i get this error:
Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
I have the latest version of mopidy and can ping spotify.com
Help?
Thank you

**Comment by kingosticks** [comment]
This is most likely a problem with your network or a localised issue with the Spotify service in your area - I have no problems logging in to the service in the UK. 

User problems regarding mopidy-spotify belong at http://discuss.mopidy.com rather than here. If you continue to experience problems can you please create a post at http://discuss.mopidy.com.
